export const bootcamp = [
  {
    id: 1,
    title: "Weather App",
    desc: "Una SPA simple que toma datos de una api externa para obtener los datos del clima de diferentes ciudades",
    web: "https://weather-app-lucjanstaniszew.vercel.app/",
    img: "../assets/WeatherApp/3.jpg",
    allImgs: ["../assets/WeatherApp/1.jpg", "../assets/WeatherApp/2.jpg", "../assets/WeatherApp/3.jpg"],
    src:"https://github.com/LucjanStaniszew/Weather-App",
  },
  {
    id: 2,
    title: "IGTV App",
    desc: "Una SPA que toma los datos de una api externa para buscar peliculas. Si las encuentra muestra los titulos relacionados y los ordena en items. Se puede añadir/eliminar de favoritos en una sesion local y ver la descripción de las peliculas como tambien la portada",
    web: "https://movie-app-lucjanstaniszew.vercel.app/",
    img: "../assets/MovieApp/2.jpg",
    allImgs: ["../assets/MovieApp/1.jpg", "../assets/MovieApp/2.jpg", "../assets/MovieApp/3.jpg"],
    src:"https://github.com/LucjanStaniszew/IGTVApp",
  },
  {
    id: 3,
    title: "Timer App",
    desc: "Una aplicación simple de navegador que se puede usar de cronometro o cuenta regresiva. Se realizó aprendiendo los conceptos de React Hooks",
    web: "https://timer-app-lucjanstaniszew.vercel.app/",
    img: "../assets/Counter.jpg",
    allImgs: ["../assets/Counter.jpg"],
    src:"https://github.com/LucjanStaniszew/TimerApp",
  },
  {
    id: 4,
    title: "Pokedex",
    desc: "La primer app realizada como Full Stack Web Developer en la academia bootcamp soyHenry. En el mismo se encuentran diferentes paginas. Lo primero que vemos es una landing page con una imagen relacionada a la tematica. Luego en la home page, podemos ver los pokemones que nos traemos de la pagina, podemos filtrarlos por tipo o por si fueron creados o traidos de la pokeApi. Tambien podemos ordenarlos ascendente y descendentemente por fuerza o alfabeticamente. Haciendo click en la imagen podemos entrar en la pagina de detalles en donde encontraremos más información acerca de los pokemones. Y por ultimo tenemos la pagina de creacion de Pokemones. Esta es un formulario validado con JS para verificar que los datos ingresados sean los correctos.",
    web: "https://github.com/LucjanStaniszew/Henry-PI-Pokemon",
    img: "../assets/PokeApi/1.jpg",
    allImgs: ["../assets/PokeApi/1.jpg", "../assets/PokeApi/2.jpg", "../assets/PokeApi/3.jpg", "../assets/PokeApi/4.jpg", "../assets/PokeApi/5.jpg"],
    src: "https://github.com/LucjanStaniszew/Henry-PI-Pokemon",
  },
  {
    id: 5,
    title: "V.I.Pets",
    desc: "V.I.Pets fue el proyecto con el que nos recibimos de la academia bootcamp soyHenry como Full Stack Web Developers. Es un proyecto creado entre 8 personas que se dedica a realizar busqueda de las clinicas veterinarias de emergencia en la zona. En la misma se cuenta con un carrusel de mascotas perdidas. Cuenta con un sistema de usuarios, por lo tanto si el usuario se registra e inicia sesión, va a poder acceder a la información de las clinicas y realizar una reserva para atender a su mascota. En su perfil puede agregar a sus mascotas con sus respectivas caracteristicas y crearle un QR para adherirle al collar. Cuenta con una sesión de administrador en la cual se puede bannear y eliminar usuarios por mala conducta, asi como registrar nuevas clinicas o hacerles modificaciones a las clinicas o usuarios nuevos.",
    web: "https://vipets.vercel.app/",
    img: "../assets/VIPets/7.jpg",
    allImgs: ["../assets/VIPets/1.jpg", "../assets/VIPets/2.jpg", "../assets/VIPets/3.jpg", "../assets/VIPets/4.jpg", "../assets/VIPets/5.jpg", "../assets/VIPets/6.jpg", "../assets/VIPets/7.jpg", "../assets/VIPets/8.jpg"],
    src: "https://github.com/Navito-py/PF-PuppyPalace",
  },
  {
    id: 6,
    title: "Spotify Clone",
    desc: "Es una SPA que permite el inicio de sesion utilizando nuestra cuenta de spotify. En la misma se puede buscar artistas por nombre y ver sus respectivos albumes así como agregarlos a favoritos. Luego podemos acceder a ver todos los albumes que le hemos asignado la propiedad -Favoritos- y eliminar alguno si lo deseamos.",
    web: "https://spotify-clone-lucjanstaniszew.vercel.app/",
    img: "../assets/SpotifyClone/3.jpg",
    allImgs: ["../assets/SpotifyClone/1.jpg", "../assets/SpotifyClone/2.jpg", "../assets/SpotifyClone/3.jpg", "../assets/SpotifyClone/4.jpg"],
    src: "https://github.com/LucjanStaniszew/Luciano_Staniszewski_FrontEnd2",
  },/*
  {
    id: 7,
    title: "TodoList: Vacation",
    desc: "A simple todo list, all vanilla javascript. You can see the code by clicking the link",
    web: "https://github.com/SilviStani/Vacation-TodoList",
    img: "https://user-images.githubusercontent.com/90510746/148145113-25ef5a46-17d7-4c5f-b9e0-07716ffc0b02.png",
    allImgs: [""],
    src: "https://github.com/SilviStani/Vacation-TodoList",
  },*/
  {
    id: 8,
    title: "Portfolio",
    desc: "Mi portfolio personal",
    web: "https://lucjan-staniszew-portfolio-lucjanstaniszew.vercel.app/",
    img: "../assets/Portfolio/1.jpg",
    allImgs: ["../assets/Portfolio/1.jpg", "../assets/Portfolio/2.jpg", "../assets/Portfolio/3.jpg","../assets/Portfolio/4.jpg", "../assets/Portfolio/5.jpg"],
    src: "https://github.com/LucjanStaniszew/Lucjan-Staniszew-Portfolio",
  }
];